In [1]:
import pandas as pd
from pandas import *
import numpy as np
import csv
from sklearn.cluster import KMeans
import numpy as np

In [32]:
data = pd.read_csv('data/dataset_small.csv')
data.drop('time', axis=1, inplace=True)
data.drop('timeofday', axis=1, inplace=True)
data.drop('date', axis=1, inplace=True)
data.groupby(['isin','side']).sum()

                       price     volume
isin      side
isin10    B       108.908545    3680000
          S       107.337749    3680000
isin100   B       209.721102     520000
          S       104.845419     210000
isin1000  B       654.783307    2010000
          S      3473.085896    1825000
isin10000 B        58.821086      30000
          S        59.706387    3935000
isin10004 B        42.951855      55000
          S        42.986412      60000
isin10005 B       121.338780     135000
          S       138.512820      80000
isin1001  B       259.704993      20000
          S       130.376095      10000
isin10013 B        42.767548      25000
          S        20.933811    3920000
isin10015 B        70.374667      55000
          S       111.589371      70000
isin10019 B        21.237166     100000
          S       139.643793      90000
isin1002  B       499.291226     500000
isin10023 B       943.546908    3590000
          S      2008.871002    1550000
isin10024 B     10321.366804  139870000
          S     33332.139152  130020000
isin10028 B      2619.498701   14900000
          S       804.676023    2890000
isin1003  B       222.024730      60000
isin10033 B       576.618388     750000
          S       601.627560     835000
...                      ...        ...
isin1029  B      1369.793040    7450000
          S      1040.179841    2430000
isin10291 B      4321.044449   32665000
          S      2797.879588   36505000
isin10295 B      7996.109380   37660000
          S     23873.172454   45895000
isin10300 B      1308.080641   54920000
          S      2184.519018   81370000
isin10305 B      9205.249749   56855000
          S      9680.037600   60640000
isin10311 B       109.356746     260000
isin10315 B      1379.944573   24360000
          S      1382.562567   25050000
isin10316 B      3768.831524    1165000
          S     11852.856048    2360000
isin16995 B       526.123569   12960000
          S       421.225790   11730000
isin1722  B       737.264730     135000
          S       632.990079      60000
isin2115  B       289.903866     130000
isin2218  B      1305.627057   32150000
          S      1651.372942   43300000
isin2372  B     29422.153923  686635000
          S     27290.643731  578280000
isin2872  B     21496.129272   95350000
          S     26380.803042  124945000
isin3379  B     11870.155774   63230000
          S     36197.150071  115670000
isin3443  B     16917.760540   51200000
          S     13630.884624   89035000

[161 rows x 2 columns]